---
title: "AnVIL: SRA Data"
date: "`r format(Sys.time(), '%B %d, %Y')`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
description: Description about Course/Book.
favicon: assets/AnVIL_style/anvil_favicon.ico
css: assets/AnVIL_style/style.css
---


# About this Module {-}

This module is part of a series of books for the Genomic Data Science Analysis, Visualization, and Informatics Lab-space (AnVIL) of the National Human Genome Research Institute (NHGRI). Learn more about AnVIL by visiting https://anvilproject.org or reading the [article in Cell Genomics](https://www.sciencedirect.com/science/article/pii/S2666979X21001063).

## About SRA {-}

This module will go over how to bring Sequence Read Archive (SRA) data into AnVIL.

You can check out the [SRA website](https://www.ncbi.nlm.nih.gov/sra) to learn more:

> Sequence Read Archive (SRA) data, available through multiple cloud providers and NCBI servers, is the largest publicly available repository of high throughput sequencing data. The archive accepts data from all branches of life as well as metagenomic and environmental surveys. SRA stores raw sequencing data and alignment information to enhance reproducibility and facilitate new discoveries through data analysis. 

It can be very exciting to learn how much data is at your fingertips! Once you have settled on some data to use, you'll want to bring it into AnVIL if it's not already there.

Navigate to the menu on the left to get started!

## Skills Level {-} 

::: {.notice}
_Genetics_

**Novice**: no genetics knowledge needed

_Programming skills_

**Novice**: no programming experience needed
:::

# Learning Objectives {-}

<!-- Learning objectives for this activity come from the [Genetics Core Competencies](https://genetics-gsa.org/education/genetics-learning-framework/): -->

<!-- - Objective 1 -->
<!-- - Objective 2 -->
<!-- - Objective 3 -->

<!-- Please also see the Bioinformatics core competencies for undergraduate life sciences education from NIBLSE: https://journals.plos.org/plosone/article/figure?id=10.1371/journal.pone.0196878.t002 -->

## AnVIL Collection {-}

Please check out our full collection of AnVIL and related resources below!

```{r, echo = FALSE, message = FALSE, warning = FALSE}
source("scripts/anvil_repo_table.R")

# Add below any repositories that should not be added
exclude = c(
  "anvil-intro",
  "AnVIL_Template",
  "AnVIL_Template_Test",
  "GDSCN_bookdown_style"
)

# Create table for AnVIL repos detected through the API
knitr::kable(make_anvil_repo_table(exclude), format = "html")
```
